# Generated by Django 3.0.7 on 2020-06-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNamber', models.CharField(max_length=20, verbose_name='Серийный номер')),
                ('ip', models.CharField(max_length=15, verbose_name='ip-адрес')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='PrinterFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фирма принтера')),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Фирма принтера',
                'verbose_name_plural': 'Фирмы принтеров',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Cтатус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Тип помещения')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.CreateModel(
            name='StatusP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateChangeStatus', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.Printer', verbose_name='Серийный номер')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.Status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус принтера',
                'verbose_name_plural': 'Статусы принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель принтера')),
                ('photo', models.ImageField(upload_to='')),
                ('printerFirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.PrinterFirm')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
            },
        ),
        migrations.CreateModel(
            name='LocationPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberRoom', models.CharField(max_length=10, verbose_name='Номер кабинета')),
                ('numberTutul', models.IntegerField(verbose_name='Номер титула')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('dateChange', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('serialNamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.Printer', verbose_name='Серийный номер')),
                ('typeRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.TypeRoom', verbose_name='Тип помещения')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.Zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Место расположение',
                'verbose_name_plural': 'Места расположания',
            },
        ),
    ]
