# Generated by Django 3.0.7 on 2020-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.IntegerField(unique=True, verbose_name='Титул')),
                ('room', models.CharField(max_length=10, verbose_name='Кабинет')),
                ('nubmer', models.IntegerField(verbose_name='Номер кабнета')),
                ('floor', models.IntegerField(unique=True, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Место расположения',
                'verbose_name_plural': 'Места расположения',
            },
        ),
        migrations.AlterModelOptions(
            name='printerfirm',
            options={'verbose_name': 'Фирма принтера', 'verbose_name_plural': 'Фирмы принтеров'},
        ),
        migrations.AlterModelOptions(
            name='printermodel',
            options={'verbose_name': 'Модель принтера', 'verbose_name_plural': 'Модели принтеров'},
        ),
    ]
