# Generated by Django 3.0.7 on 2020-06-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0002_auto_20200613_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='nubmer',
        ),
    ]
