# Generated by Django 3.0.7 on 2020-06-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0003_remove_location_nubmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='titul',
            field=models.IntegerField(verbose_name='Титул'),
        ),
    ]
