# Generated by Django 3.0.7 on 2020-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0004_auto_20200613_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
    ]
