# Generated by Django 3.0.7 on 2020-06-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0006_printerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=15, unique=True, verbose_name='Серийный номер')),
                ('ipAdress', models.CharField(max_length=12, unique=True, verbose_name='Ip-адрес')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.Location')),
                ('printerModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.PrinterModel')),
                ('printerStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.PrinterStatus')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
    ]
