# Generated by Django 3.0.7 on 2020-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0007_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='titul',
            field=models.CharField(max_length=10, verbose_name='Титул'),
        ),
    ]
