# Generated by Django 3.0.7 on 2020-06-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0008_auto_20200613_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='printerModel',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='printerStatus',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='PrinterStatus',
        ),
    ]
