# Generated by Django 3.0.7 on 2020-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0010_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Зона'),
        ),
    ]
