# Generated by Django 3.0.7 on 2020-06-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0013_auto_20200614_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Зона'),
        ),
    ]
