# Generated by Django 3.0.7 on 2020-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0014_auto_20200614_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Тип помещения')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
    ]
