# Generated by Django 3.0.7 on 2020-06-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0016_locationprinter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationprinter',
            options={'verbose_name': 'Место расположение', 'verbose_name_plural': 'Места расположания'},
        ),
        migrations.AlterField(
            model_name='locationprinter',
            name='numberTutul',
            field=models.IntegerField(verbose_name='Номер титула'),
        ),
        migrations.AlterField(
            model_name='locationprinter',
            name='typeRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.TypeRoom', verbose_name='Тип помещения'),
        ),
    ]
