# Generated by Django 3.0.7 on 2020-06-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0017_auto_20200614_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationprinter',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Printer.Zone', verbose_name='Зона'),
            preserve_default=False,
        ),
    ]
