# Generated by Django 3.0.7 on 2020-06-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0018_locationprinter_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationprinter',
            name='numberRoom',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер кабинета'),
        ),
    ]
