# Generated by Django 3.0.7 on 2020-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0019_auto_20200614_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Cтатус',
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
