# Generated by Django 3.0.7 on 2020-06-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0022_statusp'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationprinter',
            name='dateChange',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='locationprinter',
            name='serialNamber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Printer.Printer', verbose_name='Серийный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationprinter',
            name='numberRoom',
            field=models.CharField(max_length=10, verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='statusp',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Printer.Printer', verbose_name='Серийный номер'),
        ),
    ]
