# Generated by Django 3.0.7 on 2020-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmCatrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фирма картриджа')),
            ],
            options={
                'verbose_name': 'Фирма картриджа',
                'verbose_name_plural': 'Фирмы картриджей',
            },
        ),
    ]
