# Generated by Django 3.0.7 on 2020-06-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0002_firmcatrige'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='imageColor',
        ),
    ]
