# Generated by Django 3.0.7 on 2020-06-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0003_remove_color_imagecolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmCatrige',
        ),
    ]
