# Generated by Django 3.0.7 on 2020-06-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0006_catrigemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catrigemodel',
            options={'verbose_name': 'Модель картриджа', 'verbose_name_plural': 'Модели картриджей'},
        ),
        migrations.RenameField(
            model_name='catrigemodel',
            old_name='adword',
            new_name='color',
        ),
    ]
