# Generated by Django 3.0.7 on 2020-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0007_auto_20200621_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtatusCatrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус картриджа',
                'verbose_name_plural': 'Статусы картриджей',
            },
        ),
    ]
