# Generated by Django 3.0.7 on 2020-06-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0008_ctatuscatrige'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CtatusCatrige',
            new_name='StatusCatrige',
        ),
    ]
