# Generated by Django 3.0.7 on 2020-06-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0009_auto_20200621_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=15, unique=True, verbose_name='Серийный номер')),
                ('modelCatrige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catrige.CatrigeModel', verbose_name='Модель картриджа')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
