# Generated by Django 3.0.7 on 2020-06-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0010_catrige'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscatrige',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.CreateModel(
            name='StarusC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateChange', models.DateField(auto_now=True)),
                ('catrigeStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catrige.StatusCatrige', verbose_name='Статус картриджа')),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catrige.Catrige', verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Статус картриджа',
                'verbose_name_plural': 'Статусы картриджей',
            },
        ),
    ]
