# Generated by Django 3.0.7 on 2020-06-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Printer', '0003_auto_20200621_1050'),
        ('Catrige', '0011_auto_20200621_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='catrigemodel',
            name='printerModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Printer.PrinterModel', verbose_name='Модель принтера'),
            preserve_default=False,
        ),
    ]
