# Generated by Django 3.0.7 on 2020-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0012_catrigemodel_printermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='catrige',
            name='Original',
            field=models.BooleanField(default=1, verbose_name='Оригенал'),
            preserve_default=False,
        ),
    ]
