# Generated by Django 3.0.7 on 2020-06-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0014_auto_20200626_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarusC',
        ),
    ]
