# Generated by Django 3.0.7 on 2020-06-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0015_delete_starusc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataExtradition', models.DateField(verbose_name='Дата выдачи')),
                ('serialNumberCatrige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catrige.Catrige', verbose_name='Серийный номер картриджа')),
                ('statusExtradition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catrige.StatusCatrige', verbose_name='Статус картриджа')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
            },
        ),
    ]
