# Generated by Django 3.0.7 on 2020-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0018_jurnalcatrige'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalcatrige',
            name='dateExtation',
            field=models.DateField(),
        ),
    ]
