# Generated by Django 3.0.7 on 2020-06-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catrige', '0019_auto_20200626_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalcatrige',
            name='dateExtation',
            field=models.DateField(auto_now=True),
        ),
    ]
